name: clauviver_anamnese
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  csv: ^6.0.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  file_saver: ^0.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  cupertino_icons: ^1.0.8

# PRIMEIRO o splash screen
flutter_native_splash:
  color: "#586e26"
  image: assets/icon/splash_square.png
  android: true

# DEPOIS o launcher icon
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
